# Dependencies
#markdown:         redcarpet
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            UB3RS3C
tagline:          'Humble Security Guy'
description:      'Learning stuff, one topic at a time.'
url:              https://ub3rsick.github.io
baseurl:          /

author:
  name:           'Rizal Muhammed'
  url:            https://twitter.com/ub3rsick

paginate:         5
plugins: [jekyll-paginate]
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
